name: starlink-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<1.24  # skyfield需要較舊版本的numpy
  - pandas
  - matplotlib
  - tqdm
  - scipy
  - plotly
  - r-base>=4.0
  - r-tidyverse
  - r-plotly
  - r-dt
  - r-jsonlite
  - r-lubridate
  - r-htmlwidgets
  - r-knitr
  - r-kableextra
  - r-viridis
  - r-rmarkdown
  - r-reticulate
  - r-leaflet
  - r-leaflet.extras
  - r-targets
  - r-shiny
  - r-ggplot2
  - r-gridextra
  - r-htmltools
  - r-scales
  - r-renv
  - r-quarto
  - r-tinytex
  - openssl
  - ca-certificates
  - jupyter
  - pip
  - pip:
    - ephem
    - pygc
    - skyfield==1.46 