name: starlink-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21,<1.24  # skyfield需要較舊版本的numpy
  - pandas>=1.3
  - matplotlib>=3.5
  - tqdm
  - scipy
  - plotly>=5.0
  - requests
  - openssl
  - ca-certificates
  - fontconfig  # 字型配置支援
  - jupyter
  - flask  # 新增 Flask
  - pip
  - pip:
    - skyfield==1.46
    - ephem
    - pygc 