name: starlink-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - r-base=4.3
  - r-reticulate
  - r-tidyverse
  - r-lubridate
  - r-sf
  - r-ggplot2
  - r-leaflet
  - r-leaflet.extras
  - r-targets
  - r-shiny
  - r-shinydashboard
  - r-survival
  - r-plotly
  - r-knitr
  - r-kableextra
  - r-gridextra
  - r-rmarkdown
  - r-htmltools
  - r-dt
  - r-scales
  - r-renv
  - r-jsonlite
  - r-htmlwidgets
  - r-quarto
  - r-tinytex
  - r-pak
  - r-curl
  - r-httr
  - r-xml2
  - libcurl
  - libxml2
  - openssl
  - ca-certificates
  - pip
  - numpy<1.24
  - pip:
    - skyfield==1.46
    - pandas
    - matplotlib
    - tqdm
    - jupyter
    - scipy
    - plotly 