name: starlink-env
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  # Python 環境
  - python=3.9
  - pip
  
  # Python 科學計算套件
  - numpy>=1.21,<1.24
  - pandas>=1.3
  - matplotlib>=3.5
  - scipy
  - requests
  - tqdm
  
  # R 環境和核心套件
  - r-base>=4.1
  - r-shiny
  - r-shinydashboard
  - r-plotly
  - r-ggplot2
  - r-dplyr
  - r-scales
  - r-dt
  - r-jsonlite
  - r-reticulate
  
  # 通過 pip 安裝的 Python 套件
  - pip:
    - skyfield==1.46
    - ephem
    - pygc
    - plotly>=5.0 